name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v1
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.6'
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: SwiftTheming
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
