name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
